sudo: required

services:
- docker

env:
  global:
  - secure: YKv+Zn33nIaTxBzE/l9U3W//PZgunwwyvVL8/Hfdt5uyv3cPn1gdI1CUQdKLLwrqOn2Ngz017yAObDPv33Txdrl/xfACb39kM0obBWrvFbX1WkEioLOMHn8D6jItstvGQAUPGWpE7CArVkkV/6TCBKu9AiXviAf2aKHB+YNjqBKn/iTsqq4D0cOS6sFhsy8RMYqTJP+Jue3yEsWTd4nxDAo0Ke00h6nRmdIq4VL8liyq0pCC9b/fmy38GLCthKI9YnUri5ZfY/Zw9eJztJdHJyLV6sCyAHetT5+33tWYyxodQTu4f6AtubJf6phyZf3fcBr+3YFM/VCybkQzZPs0x6GLYjeQXk5xHpfAK+KkXmraSVFGTurQlT+U4LOGjhX1VL05N7zmTyafM7B0eyhW2wOHebMWMMcFGxAo4W2YKM2qYC/QPqonbIMLjA8U+5/5bcPIeeqZhbq+PmO/Wzbjr0qZhwsPW34YNyh2uY7t/5f2r+92gwen9/4hpMe1x7PwJxH4q0IGSvaEH5eGddVAuJEZvBUxW2cQKpHpDUDaIKDUrreS8vw3rJb7XjsZtX67jLsgGwFWtln/HNRpiapNpoBALo9EItEf3K4eGl8e/S7HkVbslJ915SrOvf3ZTVY/N54gCbaI3DnOkqWwRJujKJLsODfsPBxqJolEYB1sWJk=
  - secure: JdWhy/UxzcRvrqj1AE/O5Omrv72EHis/9lSWFxyB2thLe5OFgBIywivH0t8wD/h6VCzO7esXCOuAEcMlWJT3wRMXPXNlYodkQJBk9pTKB/3+yXZhYzVXPfSx9CdFwUJG/5RNTKBAP2KuTd/Nz7T+/IncgXEtPiW6Pbkz2v8R+a6GXqqrb7EoMw3pMqsFF5XJTRvDGohOvCdRzDOXcixYJi0UEGe8XWBSus3dz/BwCnzotukwA5kGYtM4e+qOOO4PW3kRl/kMJa96NJLMEyLKIGD3VmTnB16ioKuse2vd6us2JScOTZesqm75iCAaJNMwxKpAWEC0y1jexJ9SzMzOV0I6pag+zuUzH2bLq2yk6HcOqVpTr/fUg7OAU8uxTXQ49pfl0rvtYEhmuANqGxHZNOp4FZpGV6T25HiExE4f+Vl7+KtJqVr4CAwjZhBE1TpWBNRqfSIP70YwBykF5ELDoUgXhkJtc0bANVKCgbbqsOZSC0NqbzFVgDmFgtAA4fqRIUtWOQD7AvxVWzxawHQFMqn1mQfaYSuoTSuEQxkGikF5L0ihiBWwOQLmzThDz7qMuXJTLBB1mlZC+DZrTjhBk0zSQy3wZD4pjZL2kwEkjGyaYxyAFuVp995fILo+Pg2TCdiogAKbOqFogHMtv94XAqU5B8sy63joOV31bLJre6s=

before_install:
- docker pull shakataganai/nginx-accessfabric:latest
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD

script:
- "./build.sh"

notifications:
  email: false
  slack: false